Test: testing
Azure/k8s-work-api pull request #52
Opened 2022-07-07 17:33 UTC by aagusuab

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Caravel's [Code of conduct](https://github.com/Azure/k8s-work-api/blob/master/code-of-conduct.md).
- [ ] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

### Special notes for your reviewer

2022-07-07 23:23 UTC, Ealianis commented on pkg/controllers/suite_test.go
> +	workClient    client.Client
#### Request > Revision
While you are doing this major refactoring please take care of naming conventions. This is no longer a workClient. It is simply a client. But is it for the Hub or Spoke?

2022-07-07 23:29 UTC, Ealianis commented on pkg/controllers/suite_test.go
> +	workClient    client.Client
I'm going to make the case for redundant clients even if the underlying REST config is the same, regardless of whether or not it is mocked or because we are dual purposing a cluster; which is the case with the E2E tests. 

"Story telling" is an important part of documenting one's code. If a test is to update a Work obj on the Hub, then there should be a HubClient, and a SpokeClient for spoke cluster calls. This code is lean now , but future code bases may become more complicated. Any way to reduce cognitive overhead is a win.

2022-07-08 22:04 UTC, aagusuab commented on pkg/controllers/suite_test.go
> +	workClient    client.Client
While I do think this is important, I believe this is not part of the scope of this PR, and that we should have a different PR to refactor the naming changes. 
Since there are already a lot of changes / possible breaks with this PR, I'll focus on the removal of clientset only for now.

2022-07-08 22:45 UTC, Ealianis commented on deploy/admin_clusterrole_binding.yaml
> +  name: work-controller-binding
Why?

2022-07-08 22:49 UTC, Ealianis commented on pkg/controllers/apply_controller_integration_test.go
>  				Expect(err).ToNot(HaveOccurred())
#### Comment > Style
Empty line between multi-line statement and new line. Otherwise it makes it hard to determine where the multiline statement ends.

2022-07-08 22:51 UTC, Ealianis commented on pkg/controllers/apply_controller_integration_test.go
>  				if err == nil {
#### Comment > Style
Missing empty line below multiline statement.

2022-07-08 22:52 UTC, Ealianis commented on pkg/controllers/apply_controller_integration_test.go
>  				if err == nil {
#### Comment > Style
Missing empty line below multiline statement.

2022-07-08 23:00 UTC, Ealianis commented on pkg/controllers/finalize_controller.go
> +			return ctrl.Result{}, err
#### Request > Revision
You are missing the logs here. We log on if the delete fails, we should log if the retrieve fails.

2022-07-08 23:05 UTC, Ealianis commented on pkg/controllers/work_status_controller_integration_test.go
> +
#### Comment > Style
Unnecessary empty line.

2022-07-08 23:08 UTC, Ealianis commented on pkg/controllers/work_status_controller_integration_test.go
> +			err = workClient.Update(context.Background(), &currentWork)
#### Request > Clarity
Does this client's CRUD func have overloaded signatures? i.e. do they have a func that takes the metav1.<verb>Options{} ?

2022-07-08 23:09 UTC, Ealianis commented on pkg/controllers/work_status_controller_integration_test.go
>  		" isn't a respective AppliedResourceMeta.", func() {
#### Comment > Style
This multiline string seems unnecessary as the length of the line is near the width of below lines such as  145.

2022-07-08 23:10 UTC, Ealianis commented on tests/e2e/apply_test.go
> +	v1 "k8s.io/api/core/v1"
#### Comment > Style
Import sort is incorrect.

2022-07-08 23:12 UTC, Ealianis commented on tests/e2e/apply_test.go
> +					var cm v1.ConfigMap
#### Comment > General
This whole e2e test structure is being refactored, but I'm curious if this move was needed?

2022-07-08 23:14 UTC, Ealianis commented on tests/e2e/apply_test.go
> +					err = spokeKubeClient.CoreV1().ConfigMaps(configMapNamespace).Delete(context.Background(), configMapName, metav1.DeleteOptions{})
#### Comment > General
Why the delete? The update manifest change will reapply the manifest spec and update the existing ConfigMap. That is the point of the test.

2022-07-08 23:16 UTC, Ealianis commented on tests/e2e/apply_test.go
> +				BeforeEach(func() {
#### Comment > General
Again, I don't see why you are deleting something that is being created moments ago.
The It blocks will execute all BeforeEach blocks from the outer most to the inner most blocks. So this Context is creating work with the full set of manifests that have been appended (which include a configmap), and then you delete it. Why?

2022-07-08 23:17 UTC, Ealianis commented on tests/e2e/apply_test.go
> +	return &retrievedAppliedWork, nil
#### Comment > Style
I won't make this comment again, but empty is missing above this return.

2022-07-11 13:16 UTC, aagusuab commented on pkg/controllers/work_status_controller_integration_test.go
> +			err = workClient.Update(context.Background(), &currentWork)
It does have the ability to take the metav1.Options{} (overloaded as you mentioned).
The parameter takes the client.UpdateOption:

> type UpdateOptions struct {
	// When present, indicates that modifications should not be
	// persisted. An invalid or unrecognized dryRun directive will
	// result in an error response and no further processing of the
	// request. Valid values are:
	// - All: all dry run stages will be processed
	DryRun []string

	// FieldManager is the name of the user or component submitting
	// this request.  It must be set with server-side apply.
	FieldManager string

	// Raw represents raw UpdateOptions, as passed to the API server.
	Raw *metav1.UpdateOptions
}

2022-07-11 13:17 UTC, aagusuab commented on pkg/controllers/work_status_controller_integration_test.go
>  		" isn't a respective AppliedResourceMeta.", func() {
Undid the multiline string

2022-07-11 13:18 UTC, aagusuab commented on tests/e2e/apply_test.go
> +	v1 "k8s.io/api/core/v1"
Fixed.

2022-07-11 13:24 UTC, aagusuab commented on tests/e2e/apply_test.go
> +					var cm v1.ConfigMap
Some of the global variables such as cm, createdWork, etc wasn't being recognized properly and panicking, so I had the variables set at the function level, instead of using global variable. example:
`currentWork := workapi.Work{}
	err := hubWorkClient.Get(context.Background(), types.NamespacedName{Name: work.Name, Namespace: work.Namespace}, &currentWork)`

2022-07-11 13:26 UTC, aagusuab commented on tests/e2e/apply_test.go
> +					err = spokeKubeClient.CoreV1().ConfigMaps(configMapNamespace).Delete(context.Background(), configMapName, metav1.DeleteOptions{})
I deleted these lines, I believe I was checking if some configmaps are correctly being deleted or not,
(Test works without these lines)

2022-07-11 13:32 UTC, aagusuab commented on tests/e2e/apply_test.go
> +	return &retrievedAppliedWork, nil
I made the changes to the return statements, but not one the lines for checking error, such as:

> if err != nil {
>   return nil, err
> }

2022-07-11 13:44 UTC, aagusuab commented on deploy/admin_clusterrole_binding.yaml
> +  name: work-controller-binding
Undid this change, I thought it was already done in the previous push

2022-07-11 13:45 UTC, aagusuab commented on pkg/controllers/apply_controller_integration_test.go
>  				Expect(err).ToNot(HaveOccurred())
I did go through the comments, and made comments to at least the ones that clearly was an error.

2022-07-11 13:45 UTC, aagusuab commented on pkg/controllers/apply_controller_integration_test.go
>  				if err == nil {
resolved.

2022-07-11 14:07 UTC, aagusuab commented on tests/e2e/apply_test.go
> +				BeforeEach(func() {
I had it to test out if configmap was being deleted correctly, removed it, e2e still works fine after deleting this line.

2022-07-11 19:28 UTC, aagusuab commented on pkg/controllers/finalize_controller.go
> +			return ctrl.Result{}, err
I have added the logging here.

2022-07-11 19:29 UTC, aagusuab commented on pkg/controllers/apply_controller_test.go
> +					Name:      "test-work",
I have went through, and removed everything that seemed unnecessary.

2022-07-11 21:24 UTC, ryanzhang-oss commented on pkg/controllers/finalize_controller.go
> +		err := r.spokeClient.Get(ctx, types.NamespacedName{
why get?

2022-07-12 00:08 UTC, aagusuab commented on pkg/controllers/finalize_controller.go
> +		err := r.spokeClient.Get(ctx, types.NamespacedName{
This is necessary because the Delete function takes the pointer of an object, 
which this Object is retrieved with the Get function.

2022-07-12 06:36 UTC, ryanzhang-oss requested changes
I wonder where is the apply_controller.go?

2022-07-12 06:54 UTC, ryanzhang-oss commented on pkg/controllers/apply_controller_integration_test.go
> +				return err == nil
err == workClient.Update(

2022-07-12 06:54 UTC, ryanzhang-oss commented on pkg/controllers/finalize_controller.go
> +		err := r.spokeClient.Get(ctx, types.NamespacedName{
the delete only cares about the gvk and name which doesn't need to come from a get.....

2022-07-12 06:54 UTC, ryanzhang-oss commented on pkg/controllers/finalize_controller_unit_test.go
> +			spokeClient: test.NewMockClient()},
why do you need both the client and spokeClient?

2022-07-12 06:54 UTC, ryanzhang-oss commented on tests/e2e/apply_test.go
> +	_ = hubWorkClient.Get(context.Background(), types.NamespacedName{
why get again?

2022-07-12 06:54 UTC, ryanzhang-oss commented on tests/e2e/apply_test.go
> +			return err
again, please read the lib code.

2022-07-12 06:54 UTC, ryanzhang-oss commented on tests/e2e/apply_test.go
> +	updatedWork, err := retrieveWork(work.Namespace, work.Name)
why add this?

2022-07-13 19:18 UTC, aagusuab commented
Will move the PR here: https://github.com/Azure/k8s-work-api/pull/59

2022-07-13 19:18 UTC, closed without merging